name: Next.js CI/CD

on:
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.1

            - name: Set up Node.js
              uses: actions/setup-node@v4.0.0
              with:
                  node-version: "20.9.0"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Run Cypress tests
              uses: cypress-io/github-action@v6.6.0
              with:
                  config-file: cypress.config.js
                  start: pnpm start
                  wait-on: "http://localhost:3000"
                  wait-on-timeout: 60
                  install: false
